services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin123
    volumes:
      - couchdb_data:/opt/couchdb/data

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

  qs-cron-healthcheck:
    build:
      context: ./qs-cron-healthcheck
      dockerfile: Dockerfile
    container_name: qs-cron-healthcheck
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./qs-cron-healthcheck/.env
    volumes:
      - ./qs-cron-healthcheck:/app

  ms-healthcheck-report:
    build:
      context: ./ms-healthcheck-report
      dockerfile: Dockerfile
    container_name: ms-healthcheck-report
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ./ms-healthcheck-report/.env
    volumes:
      - ./ms-healthcheck-report:/app

  ms-healthcheck-proxy:
    build:
      context: ./ms-healthcheck-proxy
      dockerfile: Dockerfile
    container_name: ms-healthcheck-proxy
    restart: unless-stopped
    ports:
      - "3003:3003"
    env_file:
      - ./ms-healthcheck-proxy/.env
    volumes:
      - ./ms-healthcheck-proxy:/app

  healthcheck-frontend:
    build:
      context: ./healthcheck-frontend
      dockerfile: Dockerfile
    container_name: healthcheck-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./healthcheck-frontend:/app

volumes:
  couchdb_data:
  rabbitmq_data:
