version: '3.8'
services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin123
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
